#!/usr/bin/env node
/* Builds offline-manifest.js: the list of everything the site needs to run
   with no network, plus a version stamp.

   Run it whenever files are added, removed, or their ?v= is bumped:
       node scripts/precache.js
   The service worker names its cache after the version, so a changed version
   throws away the old cache on the next activate. If you forget to run this,
   a plane-mode download simply fetches the previous list - the site still
   works online, so this fails quietly rather than loudly. That is why it is
   in the pre-push checks in CLAUDE.md. */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SKIP = new Set(['.git', 'scripts', 'node_modules', '.github']);
const ASSET = /\.(html|js|css|webmanifest|png|svg|json)$/i;

function walk(dir, out = []){
  for (const name of fs.readdirSync(dir)){
    if (SKIP.has(name)) continue;
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (ASSET.test(name)) out.push('/' + path.relative(ROOT, full).split(path.sep).join('/'));
  }
  return out;
}

/* The pages ask for assets/toy.js?v=6, not assets/toy.js, and a service worker
   caches by URL. Collect the exact strings the pages actually request. */
function referenced(files){
  const found = new Set();
  const re = /(?:src|href)\s*=\s*["']([^"']+)["']|from\s*['"]([^'"]+)['"]|importScripts\(\s*['"]([^'"]+)['"]/g;
  for (const f of files){
    if (!/\.(html|js)$/i.test(f)) continue;
    const text = fs.readFileSync(path.join(ROOT, f.slice(1)), 'utf8');
    const dir = path.posix.dirname(f);
    let m;
    while ((m = re.exec(text))){
      const raw = m[1] || m[2] || m[3];
      if (!raw || /^(https?:|data:|mailto:|#|\/\/)/.test(raw)) continue;
      const url = raw.startsWith('/') ? raw : path.posix.normalize(path.posix.join(dir, raw));
      if (!ASSET.test(url.split('?')[0])) continue;
      found.add(url);
    }
  }
  return found;
}

const files = walk(ROOT).sort();
const urls = new Set(['/']);                 // the hub, by the address people use
for (const f of files){
  urls.add(f);
  if (f.endsWith('/index.html')) urls.add(f.replace(/index\.html$/, ''));
}
for (const u of referenced(files)) urls.add(u);

const list = [...urls].sort();

/* The version is a hash of the whole site, with two things taken out of the
   input: the stamps this script writes (otherwise stamping changes the hash,
   which changes the stamp, and it never settles) and offline-manifest.js
   itself, which is generated and contains the version. */
const TEXT = /\.(html|js|css|webmanifest|json|svg)$/i;
/* Strip every stamp this script writes, whatever it is attached to. A
   twelve-character hex version is only ever ours; the hand-written ones
   like ?v=7 and ?v=0.19.0 are left alone and do count towards the hash. */
const unstamp = t => t.replace(/\?v=[0-9a-f]{12}(?![0-9a-f])/g, '');
const hash = crypto.createHash('sha1');
for (const f of files){
  if (f === '/offline-manifest.js') continue;
  const full = path.join(ROOT, f.slice(1));
  hash.update(f);
  hash.update(TEXT.test(f) ? unstamp(fs.readFileSync(full, 'utf8')) : fs.readFileSync(full));
}
const version = hash.digest('hex').slice(0, 12);

const bytes = files.reduce((n, f) => n + fs.statSync(path.join(ROOT, f.slice(1))).size, 0);
const out =
`/* Generated by scripts/precache.js - do not edit by hand.
   ${files.length} files, ${(bytes / 1024).toFixed(0)} KB, ${list.length} URLs. */
self.OFFLINE = {
  version: '${version}',
  bytes: ${bytes},
  urls: ${JSON.stringify(list, null, 0).replace(/","/g, '",\n    "').replace('["', '[\n    "').replace('"]', '"\n  ]')}
};
`;
fs.writeFileSync(path.join(ROOT, 'offline-manifest.js'), out);

/* Stamp the version into every URL that loads the worker or its manifest.
   Cloudflare gives JS a four hour browser cache no matter what _headers says,
   and it will happily cache the site's 200-fallback HTML against a path that
   did not exist yet - which is exactly what happened the first time sw.js was
   deployed, leaving registration broken for four hours because the worker was
   served as text/html. A version in the URL sidesteps the whole problem, and
   makes every later worker update land immediately too. */
function stamp(file, patterns){
  const full = path.join(ROOT, file);
  let text = fs.readFileSync(full, 'utf8'), before = text;
  for (const re of patterns) text = text.replace(re, (m, pre) => pre + '?v=' + version);
  if (text !== before){ fs.writeFileSync(full, text); return true; }
  return false;
}
const SW    = [/(\/sw\.js)(\?v=[0-9a-f]*)?/g];
const MAN   = [/(\/offline-manifest\.js)(\?v=[0-9a-f]*)?/g];
/* matter.min.js and the icons get the same treatment. Cloudflare will cache
   the site's 200-fallback HTML against a path that does not exist yet, for
   four hours, and it does not care that the file arrived in between - so any
   NEW path is poisoned if anything requested it before the deploy landed.
   That took out matter.js for six games, online as well as off. Stamping the
   URL with the site version means every deploy lands somewhere unpoisoned. */
const MATTER = [/(shared\/matter\.min\.js)(\?v=[^"'\s]*)?/g];
const ICONS  = [/(\/assets\/icons\/[a-z0-9-]+\.png)(\?v=[0-9a-f]*)?/g];
let stamped = 0;
if (stamp('sw.js', MAN)) stamped++;
for (const f of ['assets/toy.js', 'shared/kit.js', 'assets/common.js', 'index.html'])
  if (fs.existsSync(path.join(ROOT, f)) && stamp(f, SW)) stamped++;
if (stamp('shared/kit.js', MATTER)) stamped++;
for (const f of ['index.html', 'manifest.webmanifest'])
  if (stamp(f, ICONS)) stamped++;

/* Every shared file gets the site version too, everywhere it is referenced.
   Hand-written ?v= numbers had to be remembered and bumped by a person, and
   the person forgot: kit.js's contents changed without its version moving, so
   pages kept the cached old copy - which still pointed at a poisoned
   matter.js URL. One stamp, applied to everything, cannot be forgotten. */
const SHARED = ['toy.js', 'toy.css', 'kit.js', 'kit.css', 'table.js', 'qr.js', 'common.js', 'play.css'];
const SHARED_RE = SHARED.map(n =>
  new RegExp('((?:\\.\\./)?(?:assets|shared)/' + n.replace('.', '\\.') + ')(\\?v=[^"\'\\s)]*)?', 'g'));
for (const f of files){
  if (!/\.(html|js)$/i.test(f)) continue;
  if (f === '/offline-manifest.js') continue;
  if (stamp(f.slice(1), SHARED_RE)) stamped++;
}

/* Stamping rewrites the very references the URL list was read from, so after
   a stamping pass the list is one generation behind. Rebuild it here rather
   than making the next person run the script twice and wonder why the first
   run disagreed with the second. The version is unaffected: it is computed
   from content with the stamps normalised out. */
let finalList = list;
if (stamped){
  const again = new Set(['/']);
  for (const f of files){
    again.add(f);
    if (f.endsWith('/index.html')) again.add(f.replace(/index\.html$/, ''));
  }
  for (const u of referenced(files)) again.add(u);
  finalList = [...again].sort();
  fs.writeFileSync(path.join(ROOT, 'offline-manifest.js'),
    out.replace(JSON.stringify(list, null, 0)
      .replace(/","/g, '",\n    "').replace('["', '[\n    "').replace('"]', '"\n  ]'),
      JSON.stringify(finalList, null, 0)
      .replace(/","/g, '",\n    "').replace('["', '[\n    "').replace('"]', '"\n  ]')));
}
console.log('offline-manifest.js  version ' + version + '  ' + finalList.length + ' urls  ' +
            (bytes / 1024).toFixed(0) + ' KB' + (stamped ? '  (stamped ' + stamped + ' files)' : ''));
