#!/usr/bin/env node
/* Builds offline-manifest.js: the list of everything the site needs to run
   with no network, plus a version stamp.

   Run it whenever files are added, removed, or their ?v= is bumped:
       node scripts/precache.js
   The service worker names its cache after the version, so a changed version
   throws away the old cache on the next activate. If you forget to run this,
   a plane-mode download simply fetches the previous list - the site still
   works online, so this fails quietly rather than loudly. That is why it is
   in the pre-push checks in CLAUDE.md. */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SKIP = new Set(['.git', 'scripts', 'node_modules', '.github']);
const ASSET = /\.(html|js|css|webmanifest|png|svg|json)$/i;

function walk(dir, out = []){
  for (const name of fs.readdirSync(dir)){
    if (SKIP.has(name)) continue;
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, out);
    else if (ASSET.test(name)) out.push('/' + path.relative(ROOT, full).split(path.sep).join('/'));
  }
  return out;
}

/* The pages ask for assets/toy.js?v=6, not assets/toy.js, and a service worker
   caches by URL. Collect the exact strings the pages actually request. */
function referenced(files){
  const found = new Set();
  const re = /(?:src|href)\s*=\s*["']([^"']+)["']|from\s*['"]([^'"]+)['"]|importScripts\(\s*['"]([^'"]+)['"]/g;
  for (const f of files){
    if (!/\.(html|js)$/i.test(f)) continue;
    const text = fs.readFileSync(path.join(ROOT, f.slice(1)), 'utf8');
    const dir = path.posix.dirname(f);
    let m;
    while ((m = re.exec(text))){
      const raw = m[1] || m[2] || m[3];
      if (!raw || /^(https?:|data:|mailto:|#|\/\/)/.test(raw)) continue;
      const url = raw.startsWith('/') ? raw : path.posix.normalize(path.posix.join(dir, raw));
      if (!ASSET.test(url.split('?')[0])) continue;
      found.add(url);
    }
  }
  return found;
}

const files = walk(ROOT).sort();
const urls = new Set(['/']);                 // the hub, by the address people use
for (const f of files){
  urls.add(f);
  if (f.endsWith('/index.html')) urls.add(f.replace(/index\.html$/, ''));
}
for (const u of referenced(files)) urls.add(u);

const list = [...urls].sort();
const hash = crypto.createHash('sha1');
for (const f of files) hash.update(f).update(fs.readFileSync(path.join(ROOT, f.slice(1))));
const version = hash.digest('hex').slice(0, 12);

const bytes = files.reduce((n, f) => n + fs.statSync(path.join(ROOT, f.slice(1))).size, 0);
const out =
`/* Generated by scripts/precache.js - do not edit by hand.
   ${files.length} files, ${(bytes / 1024).toFixed(0)} KB, ${list.length} URLs. */
self.OFFLINE = {
  version: '${version}',
  bytes: ${bytes},
  urls: ${JSON.stringify(list, null, 0).replace(/","/g, '",\n    "').replace('["', '[\n    "').replace('"]', '"\n  ]')}
};
`;
fs.writeFileSync(path.join(ROOT, 'offline-manifest.js'), out);
console.log('offline-manifest.js  version ' + version + '  ' + list.length + ' urls  ' +
            (bytes / 1024).toFixed(0) + ' KB');
